name: Build, Lint, Test and Measure Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-failure }}
    permissions:
      contents: read
    env:
      NO_SERIALPORT_INSTALL: 1

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node-version: 14.x
            allow-failure: false
          - os: ubuntu-latest
            node-version: 16.x
            allow-failure: false
          - os: ubuntu-latest
            node-version: 18.x
            allow-failure: false
          - os: ubuntu-latest
            node-version: 20.x
            allow-failure: true
          - os: windows-latest
            node-version: 14.x
            allow-failure: false
          - os: windows-latest
            node-version: 16.x
            allow-failure: false
          - os: windows-latest
            node-version: 18.x
            allow-failure: false
          - os: windows-latest
            node-version: 20.x
            allow-failure: true

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        npm install -g grunt-cli
        npm install

    # - name: Validate Examples
    #   run: |
    #     grunt test-examples

    - name: Linting
      run: |
        grunt jshint jscs

    - name: Run Unit Tests
      run: |
        grunt nodeunit

    # - name: Run Test Coverage
    #   run: |
    #     npm run test-cover
    #     npm run coveralls
